import os
import shutil
import subprocess
from pathlib import Path

HYPRLAND_DIR = Path.home() / ".config/hypr/"

HYPRLAND_CONFIG = HYPRLAND_DIR / "hyprland.lua"
CONFIG_DIR = HYPRLAND_DIR / "configs"


def _edit(file):
    defined = os.environ.get("VISUAL") or os.environ.get("EDITOR")
    if defined:
        defined = defined.split()[0]

    editor = None
    for program in [defined, "nvim", "micro", "vim", "emacs", "nano", "vi"]:
        if program and shutil.which(program):
            editor = program
            break

    if not editor:
        raise Exception("Could not find editor")

    subprocess.run([editor, file])


def _normalize_path(path: str | Path, base: str | Path) -> Path:
    path = Path(path).expanduser()

    if not path.is_absolute():
        path = Path(base) / path

    return path.resolve()


def _update_config():
    with open(HYPRLAND_CONFIG, "w") as f:
        f.write("--$AUTOMATIC CONFIG$\n")
        f.write("-- Changes made here will NOT save!\n\n")
        for config in CONFIG_DIR.iterdir():
            if config.name.startswith("."):  # disabled
                continue
            f.write(f'require("./configs/{config.name}")\n')


def migrate_config():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    if not HYPRLAND_CONFIG.exists():
        (CONFIG_DIR / "base.lua").touch()
        _update_config()
        return

    shutil.copy(HYPRLAND_CONFIG, CONFIG_DIR / "~old.lua")

    with open(HYPRLAND_CONFIG, "r") as old, open(CONFIG_DIR / "base.lua", "a") as new:
        for line in old.readlines():
            if not line.startswith("source"):
                new.write(line)
                continue

            _, path = line.split("=")
            absPath = _normalize_path(path.strip(), HYPRLAND_DIR)
            absPath.rename(CONFIG_DIR / absPath.name)
    _update_config()


def is_autogenerated():
    if not HYPRLAND_CONFIG.exists():
        return False

    with open(HYPRLAND_CONFIG, "r") as f:
        start = f.readline()
        if start == "--$AUTOMATIC CONFIG$":
            return True

        for line in f.readlines():
            line = line.strip()
            if len(line) > 0 and not (
                line.startswith("--") or line.startswith("require")
            ):
                return False

    return True


def is_old():
    if (HYPRLAND_DIR / "hyprland.conf").exists():
        if not HYPRLAND_CONFIG.exists():
            return True
    return False


def list_configs() -> dict[str, bool]:
    """Lists the names of all configs, and whether they are disabled or not"""
    configs = {}
    for config in CONFIG_DIR.iterdir():
        configs[config.stem.removeprefix(".")] = config.name.startswith(".")
    return configs


def edit_config(name: str):
    config = get_config(name)
    if not config:
        if not name.endswith(".lua"):
            name += ".lua"
        config = CONFIG_DIR / name

    _edit(config)
    _update_config()


def toggle_config(name: str, visible: bool):
    config = get_config(name)
    if not config:
        return

    last_state = not config.name.startswith(".")
    if last_state == visible:
        return

    name = config.name.removeprefix(".") if visible else f".{config.name}"
    config.rename(config.parent / name)

    _update_config()


def remove_config(name: str):
    config = get_config(name)
    if not config:
        return

    config.unlink()
    _update_config()


def get_config(name: str):
    if not name.endswith(".lua"):
        name += ".lua"
    path = CONFIG_DIR / name

    if path.exists():
        return path

    hidden_path = CONFIG_DIR / f".{name}"
    if hidden_path.exists():
        return hidden_path

    return None


def import_config(path: Path):

    if not path.exists():
        raise Exception(f"Config {path} does not exist")

    if (CONFIG_DIR / path.name).exists():
        raise Exception(f"Config {path.name} already exists")

    if not path.name.endswith(".lua"):
        path = path.with_suffix(".lua")

    shutil.copy(path, CONFIG_DIR)
    _update_config()
    return path


def merge_configs(first_name: str, second_name: str, newName: str):
    first_config = get_config(first_name)
    if not first_config:
        raise Exception(f"Config {first_name} does not exist")

    second_config = get_config(second_name)
    if not second_config:
        raise Exception(f"Config {second_name} does not exist")

    newName = newName if newName.endswith(".lua") else f"{newName}.lua"
    new_path = CONFIG_DIR / newName
    if new_path.exists() or (CONFIG_DIR / f".{newName}").exists():
        raise Exception(f"Config {newName} already exists")

    with open(new_path, "w") as merged:
        for index, source in enumerate([first_config, second_config]):
            if index > 0:
                merged.write("\n")
            merged.write(f"# Merged from {source.name.removeprefix('.')}\n")
            with open(source, "r") as source_file:
                contents = source_file.read()
                merged.write(contents)
                if contents and not contents.endswith("\n"):
                    merged.write("\n")

    _update_config()
    return new_path


def rename_config(name: str, newName: str):
    config = get_config(name)
    if not config:
        return

    newName = newName if newName.endswith(".lua") else f"{newName}.lua"
    config.rename(CONFIG_DIR / newName)
    _update_config()
