from hyprconfig import config
import typer

app = typer.Typer()

def check_config() -> bool:
    if config.is_autogenerated():
        return True

    typer.echo("An existing Hyprland config was found")
    confirm = typer.confirm("Do you want to migrate it?", default=True)
    if confirm:
        config.migrate_config()
        typer.echo("Migrated!")
        typer.echo("The original config can be accessed with 'edit base.conf'")
    else:
        typer.echo("Aborting...")
        return False
    return True

def config_completions():
    return list(config.list_configs().keys())

@app.command()
def edit(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Opens a config for editing, or creates a new one"""
    if not check_config():
        return

    config.edit_config(name)

@app.command()
def add(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Creates a new config"""
    if not check_config():
        return
    if config.get_config(name):
        typer.echo(f"Config {name} already exists")
        return

    config.edit_config(name)

@app.command()
def remove(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Deletes a config"""
    if not check_config():
        return
    confirm = typer.confirm(f"Are you sure you want to delete {name}?", default=False)
    if not confirm:
        return

    config.remove_config(name)

@app.command()
def enable(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Enables a config"""
    if not check_config():
        return
    if not config.get_config(name):
        typer.echo(f"Config {name} not found")
        return

    config.toggle_config(name, True)

@app.command()
def disable(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Disables a config"""
    if not check_config():
        return
    if not config.get_config(name):
        typer.echo(f"Config {name} not found")
        return

    config.toggle_config(name, False)

@app.command("list")
def list_configs():
    """Lists all configs"""
    if not check_config():
        return

    for name, disabled in config.list_configs().items():
        if disabled:
            typer.secho(f"{name} (disabled)", fg=typer.colors.BRIGHT_BLACK)
        else:
            typer.echo(name)

@app.command()
def cat(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Prints the contents of a config"""
    if not check_config():
        return
    
    path = config.get_config(name)
    if path is None:
        typer.echo(f"Config {name} not found")
        return

    with open(path, "r") as f:
        typer.echo(f.read())


def main():
    app()