from hyprconfig import config
import typer
from pathlib import Path
import subprocess

app = typer.Typer()

def check_config() -> bool:
    if config.is_autogenerated():
        return True

    typer.echo("Your Hyprland config doesn't match the expected format.")
    confirm = typer.confirm("Would you like to migrate it?", default=True)
    if confirm:
        config.migrate_config()
        typer.echo("Migrated!")
        typer.echo("The original config can be accessed with 'edit base.conf'")
    else:
        typer.echo("Aborting...")
        return False
    return True

def config_completions():
    return list(config.list_configs().keys())

@app.command()
def edit(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Opens a config for editing"""
    if not check_config():
        return
    if not config.get_config(name):
        typer.echo(f"Config {name} not found")
        return

    config.edit_config(name)

@app.command()
def add(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Creates a new config"""
    if not check_config():
        return
    if config.get_config(name):
        typer.echo(f"Config {name} already exists")
        return

    config.edit_config(name)

@app.command()
def remove(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Permanently deletes a config"""
    if not check_config():
        return
    if not config.get_config(name):
        typer.echo(f"Config {name} not found")
        return

    confirm = typer.confirm(f"Are you sure you want to delete {name}?", default=False)
    if not confirm:
        return

    config.remove_config(name)

@app.command()
def enable(names: list[str] = typer.Argument(..., autocompletion=config_completions)):
    """Enables a config"""
    if not check_config():
        return
    for name in names:
        if not config.get_config(name):
            typer.echo(f"Config {name} not found")
            return

    for name in names:
        config.toggle_config(name, True)

@app.command()
def disable(names: list[str] = typer.Argument(..., autocompletion=config_completions)):
    """Disables a config"""
    if not check_config():
        return
    for name in names:
        if not config.get_config(name):
            typer.echo(f"Config {name} not found")
            return

    for name in names:
        config.toggle_config(name, False)

@app.command("list")
def list_configs():
    """Lists all configs"""
    if not check_config():
        return

    for name, disabled in config.list_configs().items():
        if disabled:
            typer.secho(f"{name} (disabled)", fg=typer.colors.BRIGHT_BLACK)
        else:
            typer.echo(name)

@app.command()
def cat(name: str = typer.Argument(..., autocompletion=config_completions)):
    """Prints the contents of a config"""
    if not check_config():
        return
    
    path = config.get_config(name)
    if path is None:
        typer.echo(f"Config {name} not found")
        return

    with open(path, "r") as f:
        typer.echo(f.read())

@app.command("import")
def import_command(path: str):
    """Imports a config from a filepath"""
    if not check_config():
        return
        
    patho = Path(path).expanduser()
    if not patho.is_absolute():
        patho = Path.cwd() / patho

    if not patho.exists():
        typer.echo(f"Config {patho} does not exist")
        return
    if config.get_config(patho.name):
        typer.echo(f"Config {patho.name} already exists")
        return

    final_path = config.import_config(patho)

    typer.echo(f"Imported config as {final_path.name.removesuffix('.conf')}")
    
@app.command("reload")
def reload():
    """Reloads the hyprland config"""
    if not check_config():
        return
    config._update_config()

    subprocess.run(["hyprctl", "reload"])

@app.command("rename")
def rename(name: str, new_name: str):
    """Renames a config"""
    if not check_config():
        return
    if not config.get_config(name):
        typer.echo(f"Config {name} not found")
        return
    if config.get_config(new_name):
        typer.echo(f"Config {new_name} already exists")
        return

    config.rename_config(name, new_name)

def main():
    app()